package fr.aximox.hub.utils;

import org.bukkit.inventory.ItemStack;

public enum HeadList {

    ALPHABET_X("NWE2Nzg3YmEzMjU2NGU3YzJmM2EwY2U2NDQ5OGVjYmIyM2I4OTg0NWU1YTY2YjVjZWM3NzM2ZjcyOWVkMzcifX19", "oak_wood_x"),
    ARROW_RIGHT("MTliZjMyOTJlMTI2YTEwNWI1NGViYTcxM2FhMWIxNTJkNTQxYTFkODkzODgyOWM1NjM2NGQxNzhlZDIyYmYifX19", "oak_wood_arrow_right"),
    ARROW_LEFT("YmQ2OWUwNmU1ZGFkZmQ4NGU1ZjNkMWMyMTA2M2YyNTUzYjJmYTk0NWVlMWQ0ZDcxNTJmZGM1NDI1YmMxMmE5In19fQ==", "oak_wood_arrow_left"),
    WOOD_WHAT("YmFkYzA0OGE3Y2U3OGY3ZGFkNzJhMDdkYTI3ZDg1YzA5MTY4ODFlNTUyMmVlZWQxZTNkYWYyMTdhMzhjMWEifX19", "?"),
    SLOTS("ZWVhNzU5Zjk3OWI5YjhlYTgzMWNhN2UyZDY2ZGYxNDgyOTNmMWE1MTQ3OTgzYjUyYzQ4ZWZlMmMzMTVlIn19fQ==", "penguin"),
    DEMON_SLAYER("OTU3YmJlMjczODNhMzNjMmZmM2IzYjAwZjQ2MzQ2ZmNjZWM4Zjg0YmE2NDExNGZjN2E3ODAyNTUzN2Q3OGNlMSJ9fX0=", "demon"),
    AOT("NzJlNWE5ODRjMzZlZTczMjE3Y2I0YjAzMmQyMTM2MDk2YWZiMWQ3NjEwNDU1OWExNTM5OWI5YzBjNGQyN2NmNiJ9fX0=", "AOT"),
    DEATHNOTE("M2RjNjcwYzc1ZjkzYWZiYmFiOWQ5YTJhZmUxYzNmNjE3ZTkyMTJkMzRlZTcwNDZjZmUyNjczN2VlYjQ4ZTBiMSJ9fX0=", "DEATHNOTE"),
    TAUPE_GUN("MTgxODUyOTQzZTM2YzhhM2YxZTNkMGU0OTEyNTQ5Y2JjMjA1ZDk0NzM5NGFkYmU2NWY0ZDgxZDYxMWJlMmM4NyJ9fX0=", "mole"),
    DIAMOND("NzM4YzUyMmE1YjIyMzViNDAwZTgyN2NmOTYxNTU1YTI2NGZhMmEyNTJlZDBlMzNkMWM3YzczN2ZlOGZjZDI3YyJ9fX0==", "diamond"),
    EARTH("NTU3N2M0ZGUxZjUxYTcwNzIyMDIzZTg1NmI1NDNjZDU3MGYxZDBlZTZiOWQxNjdiNTkwMjhjZTFiYzkyZTQ1OCJ9fX0=", "lobby"),
    YOUTUBE("Yzc2N2VkNzllZGU3YjU4MWRlNGM2YzczMWY1Yjg1OTg5MjRjZjQ1NmU1YTQwNDBlMjdmZGYyNWFjNjAyNTMxZCJ9fX0=", "Youtube"),
    TWITCH("ZWQyYjA1YWJlNDk3NmMwYWYxZjU0YjhkMzRlNjU2ZDE0MzgzMTc0ZmY1YzZlYmE2MTNhOGE4NDA1NDk4Y2IxNSJ9fX0=", "Twitch"),
    X("OTFiN2EwYzIxMGU2Y2RmNWEzNWZkODE5N2U2ZTI0YTAzODMxNWJiZTNiZGNkMWJjYzM2MzBiZjI2ZjU5ZWM1YyJ9fX0=", "X"),
    GREENMINUS("NWY2N2Y3N2Y5Njk3MjU1NTUzZmExNzk3OWNmNzI0MmNlN2Q3NWRkNTJmYmYzY2ZiMjZjOWFiNTRlMmE3MTkzOCJ9fX0=", "greenminus"),
    ORANGEMINUS("YWNmZjkxZGM5OWQ1ODI4MDIzZWVkZjg3Mzc5OWQyNTUzNWRhZGU2NGEyZTE2YTNiNDk4YjQxMTNlYWZkNDk2NiJ9fX0=", "orangeminus"),
    REDMINUS("NGU0YjhiOGQyMzYyYzg2NGUwNjIzMDE0ODdkOTRkMzI3MmE2YjU3MGFmYmY4MGMyYzViMTQ4Yzk1NDU3OWQ0NiJ9fX0=", "redminus"),
    GREENPLUS("YjA1NmJjMTI0NGZjZmY5OTM0NGYxMmFiYTQyYWMyM2ZlZTZlZjZlMzM1MWQyN2QyNzNjMTU3MjUzMWYifX19", "greenplus"),
    ORANGEPLUS("NTI1MGIzY2NlNzY2MzVlZjRjN2E4OGIyYzU5N2JkMjc0OTg2OGQ3OGY1YWZhNTY2MTU3YzI2MTJhZTQxMjAifX19", "orangeplus"),
    REDPLUS("YWM3MzFjM2M3MjNmNjdkMmNmYjFhMTE5MmI5NDcwODZmYmEzMmFlYTQ3MmQzNDdhNWVkNWQ3NjQyZjczYiJ9fX0=", "redplus"),
    SANGLIER("MTViNzcwMzMxNzUzMjY4ZGYwYWY0YmMzOTk5ZDVlOTE5YjY1YTJmNTRjODUzMjdkMjNiYTZlODA3YzU2ZWIifX19=", "sanglier"),
    LOUP_GAROU("MzY4ZDQzMTI5MzliYjMxMTFmYWUyOGQ2NWQ5YTMxZTc3N2Y4ZjJjOWZjNDI3NTAxY2RhOGZmZTNiMzY3NjU4In19fQ==", "werewolf");
    private final ItemStack item;

    private final String idTag;

    HeadList(String texture, String id) {
        String prefix = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUv";
        item = CreateSkull.createSkull(prefix + texture, id);
        idTag = id;

    }

    public ItemStack getItemStack() {
        return item;
    }

    public String getName() {
        return idTag;
    }

}